### ISSUE TITLE
First Issue 

### ISSUE THREAD

**Issue by grzegorzSpiewak** [joshwnj/react-starter#2]
Hey,

I've done Task 3. It helped me to understand more about structure of the components in react. 

https://github.com/grzegorzSpiewak/react-starter/tree/master/second/react-starter

**Comment by joshwnj** [comment]
Great! Any questions or things you'd like to explore deeper with tutorial 3?

**Comment by grzegorzSpiewak** [comment]
No. It really helped me to understand how to work with CSS in react :) I had some problems with understanding how to apply styles correctly. Now I'm wondering how to apply css reset. Do I just create separate css file with reset and just attache it in traditional way (in head) or can I do with with react?

**Comment by joshwnj** [comment]
> Do I just create separate css file with reset and just attache it in traditional way (in head) or can I do with with react?

either way works. I haven't used https://github.com/nfl/react-helmet but that might be a useful way to do it from react.

I think the main consideration there is whether you want the css to apply _before_ the page is rendered, or _after_ js starts to execute. For this reason, I would usually put "reset" or "general theme" css directly into the html `<head>` rather than going through react.

**Comment by grzegorzSpiewak** [comment]
it sounds reasonable :). I gees that's all for now. More questions will come with time :)
