### ISSUE TITLE
Tutorial 1 - Conditional display using the presets

### ISSUE THREAD

**Issue by mccrodp** [joshwnj/react-starter#4]
I got through Tutorial 1, got most of the way there, enough that I was happy I understood the majority of what was being asked. I did come across something that confused me, so I proceeded to go to your solution.

Why is my `props.progress` not showing the Message text and always showing the button? https://github.com/mccrodp/react-starter/blob/tutorial-1-start/src/frontend/containers/SampleForm/index.js#L13

If I change the initial state to `presets.error` it shows the error and that is checked using `props.error` in *index.js*, so I am confused why `props.progress` is not returning true. If I change the `conditional` const to check for `props.message`, then the message div is displayed as expected. Had a look at the inspector also set some breakpoints, but it didn't lead me to the answer.

**Comment by joshwnj** [comment]
Ok, I think I can see the confusion here: the `presets` object is not exposed to the pure component. It just defines the values that become props.  In other words, the reason you can't use `props.progress` is because it doesn't exist :)

We can step through things one by one, and hopefully that will illuminate this for us. First, we choose load up the preset in the stateful component:

https://github.com/mccrodp/react-starter/blob/tutorial-1-start/src/frontend/containers/SampleForm/state.js#L37

```js
  getInitialState: function () {
    return presets.progress
  },
```

`presets.progress` is defined above as this:

```js
presets.progress = {
  ...presets.init,
  message: "Submitting..."
}
```

which means "copy all of the values from `presets.init`, and also set `message: "Submitting"`"

When we render the component, these are the only values available to the component:

```js
  render: function () {
    return <Component {...this.state} />
  }
```

Does that clear it up?

**Comment by mccrodp** [comment]
Yes, it certainly does. I thought it shouldn't be exposed actually and in hindsight I've gotten confused with the preset and prop / variable naming.

I thought that as preset `error` and `loading` were available via `props.*`, then `progress` preset should be. However, it seems that those other presets also defined `error` and `loading` as actual values in the preset which would be available via props.

Thanks for that.

**Comment by joshwnj** [comment]
It's good feedback - I'll think about ways to make `presets` and `props` more distinct to avoid confusion like this
